### ISSUE TITLE
Trinkets and Baubles ran into an issue

### ISSUE THREAD

**Issue by Wxrlds** [XzeroAir/Trinkets#28]
When playing Vanilla Fix tells me Trinkets and Baubles runs into issues. Thought you might want to take a look at that
Log (from Vanillafix): https://gist.github.com/Wxrlds/f5ce875a93c25c455dfaf19a94bc3e67

**Comment by XzeroAir** [comment]
Yeah, I Noticed that the other day in a pack I was testing, It usually only happens when changing dimension, at least from what I saw, It doesn't hurt anything from what I've seen either, everything works properly, But I Am looking into it and seeing if I can figure out why it's showing that error at all

**Comment by BennyTurtle** [comment]
just had the same issue, glad your doing something about it and not ignoring it

**Comment by WhoCaresWhoIAm** [comment]
i have a problem and dont know how to fix it sadly so me and my friend both used fairy dew and cant revert back to normal now any way to fix that? like with a command or so?

**Comment by XzeroAir** [comment]
I think I've managed to fix it, None of the beta testers I have or myself could get it to happen anymore.
Try out 0.30 and let me know if it still happens for you.

**Comment by Nitess** [comment]
I play with people on the server and when people connect to the server, it causes me to freeze the game and the exact same error.  Trinkets and Baubles v0.30> vanilla fix v150 
https://gist.github.com/Nitess/c811bc3730b4768e6843c29b039cdc8f

**Comment by XzeroAir** [comment]
@Nitess Your crash is actually completely different, and it's quite the interesting crash, It's the First time i've seen that type of crash before, and the code that it's referencing in that crash hasn't changed since 0.27, did you add/change the pack in any way? and do you know if anyone else on the pack is having a similar issue?

**Comment by Nitess** [comment]
Yes, one person says that he is doing well.  Two others cite the same problem.
This is really weird.  Since such an error appears in many cases.  When a person logs on to the server.  Maybe when it comes out.  There was also a moment when I was killed by mobs, and I was spawning, and I executed the command home, and the person reported the problem.  At the time of death or teleport is not known.
We start from a powerful home PC.

**Comment by Nitess** [comment]
> @Nitess did you add/change the pack in any way?
yes have been added
BetterFoliage 2.3.1
Netherportalfix 5.3.17
OfflineSkins v6 and Optifine f5
A person who feels well seems to be using optifine E3. Personally, I did not check

**Comment by XzeroAir** [comment]
I'll continue to look into it.

@Wxrlds are you having similar issues?
and are you still having the from before?

**Comment by Wxrlds** [comment]
Since I updated the pack I have been playing on our server without anyone else online and I haven't noticed any issues so far.
I will report back when I notice anything.

**Comment by XzeroAir** [comment]
Haven't had any more reports like this for nearly a year, Considering this solved
