### ISSUE TITLE
Fairy Ring RLCraft Flying Problem

### ISSUE THREAD

**Issue by NinjaMaster0827** [XzeroAir/Trinkets#46]
I'm playing RLCraft with friends and we found a Fairy Ring. However, when we tried to use it it didn't let us fly. It shrunk us down and rendered the wings, but for some reason it didn't let us fly. I know it's not an issue with the server because allow-flight is set to true and the issue also persisted in single player. If it helps we updated everything that could be updated in the latest version of RLCraft, so the issue may have something to do with that (we're using the CurseForge Launcher as well).

**Comment by XzeroAir** [comment]
The only thing I can think of is that maybe the Setting is disabled in the Trinkets and Baubles Config, assuming you're using the default version of T&B that's included in RLCraft, If you're using the 0.31 Beta that's currently on curseforge, It's because of a change that's in the beta that makes it so you can't fly unless you use the Fairy Dew, or a potion (Which I'll most likely revert back or add a config option to toggle when 0.31 is officially released)

**Comment by NinjaMaster0827** [comment]
That's probably it. Thanks! The last time I used it it just worked, so I was a little confused

**Comment by XzeroAir** [comment]
Fixed in the latest Beta, I might add a config to toggle that on the full release of 0.31
